version: '3.3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: basil087/yamdb_final:latest
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static:/code/static
      - media:/code/media
  nginx:

    build: ./nginx 
    depends_on: 
      - web 
    ports: 
      - "80:80" 
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - static:/static
      - media:/media
    links:
      - web
volumes:
  postgres_data:
  static:
  media: